// <auto-generated />
using System;
using ASPFinalProjectNETCORE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPFinalProjectNETCORE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220219114122_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPFinalProjectNETCORE.Models.Author", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ASPFinalProjectNETCORE.Models.Book", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Author_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Publisher_Id")
                        .HasColumnType("int");

                    b.Property<int>("_BookCategory")
                        .HasColumnType("int");

                    b.Property<string>("_BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_BookPictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_Pages")
                        .HasColumnType("int");

                    b.Property<double>("_Price")
                        .HasColumnType("float");

                    b.HasKey("_Id");

                    b.HasIndex("Author_Id");

                    b.HasIndex("Publisher_Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ASPFinalProjectNETCORE.Models.Publisher", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("ASPFinalProjectNETCORE.Models.Book", b =>
                {
                    b.HasOne("ASPFinalProjectNETCORE.Models.Author", null)
                        .WithMany("_Books")
                        .HasForeignKey("Author_Id");

                    b.HasOne("ASPFinalProjectNETCORE.Models.Publisher", null)
                        .WithMany("_Books")
                        .HasForeignKey("Publisher_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
